# Generated by Django 6.0.7 on 2026-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('SALES_REP', 'Sales Rep'), ('STAFF', 'Staff'), ('SUPPLIER', 'Supplier')], default='STAFF', max_length=30),
        ),
    ]
