# Generated by Django 6.0.8 on 2026-08-21 22:40

from django.db import migrations, models


def backfill_supplier_phone(apps, schema_editor):
    Supplier = apps.get_model("inventory", "Supplier")

    Supplier.objects.filter(phone="").update(phone="N/A")
    Supplier.objects.filter(phone__isnull=True).update(phone="N/A")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.RunPython(backfill_supplier_phone),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=50, blank=False, null=False),
        ),
    ]
