# Generated by Django 6.0.7 on 2026-08-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_product_unit_price"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gt", 0)),
                name="product_unit_price_gt_zero",
            ),
        ),
    ]
